### ISSUE TITLE
Test failures when running assert on itself, fixed in PR #239

### ISSUE THREAD

**Issue by riddochc** [redding/assert#240]
Hi, I was just trying out Assert, and found that for a number of versions, it fails its own tests.
Apparently Array#choice hasn't been around for quite a while!

Here's one of the test failures I see:

ERROR: Assert::View Base should know how to build ansi styled messages
undefined method `choice' for [:pass, :fail, :error, :skip, :ignore]:Array (NoMethodError)
/home/riddochc/src/ruby/assert/test/unit/view_tests.rb:70:in `block in <class:BaseTests>'
/home/riddochc/.gem/gems/assert-2.15.0/lib/assert/test.rb:136:in `instance_eval'

**Comment by kellyredding** [comment]
Closing this as it is being addressed in #239.
